# k8s/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: demo-project
  labels:
    app: demo-project
spec:
  type: LoadBalancer
  selector:
    app: demo-project
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
