name: Develop Build and Deployment

on:
    push:
      branches: [ "develop" ]
    pull_request:
      branches: [ "develop" ]

env:
    REPO_NAME: ${{ github.repository }}
    REPO_NAME_ONLY: ${{ github.repository }} # Stores the full repository name      

jobs:
 
  development-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: Development  # Use the protected environment here

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Extract and Set Repository Name Only
      run: |
        echo "REPO_NAME_ONLY=$(echo $REPO_NAME | cut -d'/' -f2)" >> $GITHUB_ENV        
    
    #Set the image tag with current date and time
    - name: Set IMAGE_TAG variable
      id: tag
      run: echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
       docker build . --file Dockerfile --tag ghcr.io/${{ vars.ORG_NAME }}/${{ env.REPO_NAME_ONLY }}:${{ env.IMAGE_TAG }}
       docker tag ghcr.io/${{ vars.ORG_NAME }}/${{ env.REPO_NAME_ONLY }}:${{ env.IMAGE_TAG }} ghcr.io/${{ vars.ORG_NAME }}/${{ env.REPO_NAME_ONLY }}:latest

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ORG_PAT }}

    # Push the Docker image
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ vars.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker push ghcr.io/${{ vars.ORG_NAME }}/${{ env.IMAGE_NAME }}:latest 

